###################
# Core components #
###################

keycloak:
    build: components/keycloak
    container_name: cyclone-keycloak
#    command: -b 0.0.0.0
    command: -b 0.0.0.0 -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/opt/keycloak/exports/keycloak-export.json -Dkeycloak.migration.strategy=OVERWRITE_EXISTING
    restart: unless-stopped
    volumes:
        - ./data/keycloak/exports:/opt/keycloak/exports
    links:
        - keycloakdb
    expose:
        - "8080"
    ports:
        - "9080:8080"

keycloakdb:
    image: mongo:2.6
    container_name: cyclone-keycloakdb
    restart: unless-stopped
    expose:
        - "27017"

samlbridge:
    build: components/samlbridge
    container_name: cyclone-samlbridge
    restart: unless-stopped
    expose:
        - "80"
    ports:
        - "8080:80"

# Replace with the proper env variables
cacheclean:
    build: components/cache-clean
    container_name: cyclone-cache-clean
    restart: unless-stopped
    environment:
        - KEYCLOAK_ADMIN_USER=admin
        - KEYCLOAK_ADMIN_PASS=admin
        - KEYCLOAK_ADMIN_CLIENT=admin-cli
        - KEYCLOAK_REALM=master
        - PERIOD=60000
        - EXCLUDED_USERS=admin;owner;tub;uva;cnrs;guest;test1
    links:
        - keycloakdb
        - keycloak

#####################
# Wordpress example #
#####################
wordpressdb:
  image: mysql:5.7
  container_name: cyclone-wp-db
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=wordpress
  ports:
    - "3306:3306"

wordpress:
  build: components/wordpress
  container_name: cyclone-wp-website
  environment:
    - WORDPRESS_DB_PASSWORD=password
    - OIDC_URL_BASE=http://localhost:9080
  links:
    - wordpressdb:mysql
    - keycloak:keycloak
  ports:
    - "80:80"

###################
# SSH PAM Example #
###################
sshpam:
  build: components/ssh-pam
  container_name: cyclone-sshpam
  ports:
    - "7000-7050:7000-7050"
    - "2222:22"
