core config:
  dbname: wordpress
  dbuser: root
  dbpass: tastamam
core install:
  title: CYCLONE
  admin_user: admin
  admin_password: password
  admin_email: ilke.zilci@tu-berlin.de  
path: /var/www/html
url: "http://localhost"
